import { Surah } from '@/types/surah';

/**
 * German surah titles (`germanName`, refs #85) follow the Bubenheim & Elyas
 * translation tradition, cross-checked against the German Wikipedia surah
 * list ("Liste der Koransuren", deutsch column) and nurkoran.com.
 * Letter-named surahs (Qaf, Sad, Ya-Sin, Ta Ha) and proper nouns without a
 * German form (Hud, Luqman, Saba) are kept as-is.
 */
export const SURAHS: Surah[] = [
  {
    id: 1,
    name: 'ٱلْفَاتِحَةِ',
    englishName: 'Al-Faatiha',
    germanName: 'Die Eröffnung',
    revelationType: 'Meccan',
    ayahCount: 7,
  },
  {
    id: 2,
    name: 'البَقَرَةِ',
    englishName: 'Al-Baqara',
    germanName: 'Die Kuh',
    revelationType: 'Medinan',
    ayahCount: 286,
  },
  {
    id: 3,
    name: 'آلِ عِمۡرَانَ',
    englishName: 'Aal-i-Imraan',
    germanName: 'Die Sippe Imrans',
    revelationType: 'Medinan',
    ayahCount: 200,
  },
  {
    id: 4,
    name: 'النِّسَاءِ',
    englishName: 'An-Nisaa',
    germanName: 'Die Frauen',
    revelationType: 'Medinan',
    ayahCount: 176,
  },
  {
    id: 5,
    name: 'المَائـِدَةِ',
    englishName: 'Al-Maaida',
    germanName: 'Der Tisch',
    revelationType: 'Medinan',
    ayahCount: 120,
  },
  {
    id: 6,
    name: 'الأَنۡعَامِ',
    englishName: "Al-An'aam",
    germanName: 'Das Vieh',
    revelationType: 'Meccan',
    ayahCount: 165,
  },
  {
    id: 7,
    name: 'الأَعۡرَافِ',
    englishName: "Al-A'raaf",
    germanName: 'Die Höhen',
    revelationType: 'Meccan',
    ayahCount: 206,
  },
  {
    id: 8,
    name: 'الأَنفَالِ',
    englishName: 'Al-Anfaal',
    germanName: 'Die Beute',
    revelationType: 'Medinan',
    ayahCount: 75,
  },
  {
    id: 9,
    name: 'التَّوۡبَةِ',
    englishName: 'At-Tawba',
    germanName: 'Die Reue',
    revelationType: 'Medinan',
    ayahCount: 129,
  },
  {
    id: 10,
    name: 'يُونُسَ',
    englishName: 'Yunus',
    germanName: 'Jonas',
    revelationType: 'Meccan',
    ayahCount: 109,
  },
  {
    id: 11,
    name: 'هُودٍ',
    englishName: 'Hud',
    germanName: 'Hud',
    revelationType: 'Meccan',
    ayahCount: 123,
  },
  {
    id: 12,
    name: 'يُوسُفَ',
    englishName: 'Joseph',
    germanName: 'Josef',
    revelationType: 'Meccan',
    ayahCount: 111,
  },
  {
    id: 13,
    name: 'الرَّعۡدِ',
    englishName: "Ar-Ra'd",
    germanName: 'Der Donner',
    revelationType: 'Medinan',
    ayahCount: 43,
  },
  {
    id: 14,
    name: 'إِبۡرَاهِيمَ',
    englishName: 'Abraham',
    germanName: 'Abraham',
    revelationType: 'Meccan',
    ayahCount: 52,
  },
  {
    id: 15,
    name: 'الحِجۡرِ',
    englishName: 'Al-Hijr',
    germanName: 'Das steinige Land',
    revelationType: 'Meccan',
    ayahCount: 99,
  },
  {
    id: 16,
    name: 'النَّحۡلِ',
    englishName: 'An-Nahl',
    germanName: 'Die Bienen',
    revelationType: 'Meccan',
    ayahCount: 128,
  },
  {
    id: 17,
    name: 'الإِسۡرَاءِ',
    englishName: 'Al-Israa',
    germanName: 'Die nächtliche Reise',
    revelationType: 'Meccan',
    ayahCount: 111,
  },
  {
    id: 18,
    name: 'الكَهۡفِ',
    englishName: 'Al-Kahf',
    germanName: 'Die Höhle',
    revelationType: 'Meccan',
    ayahCount: 110,
  },
  {
    id: 19,
    name: 'مَرۡيَمَ',
    englishName: 'Mary',
    germanName: 'Maria',
    revelationType: 'Meccan',
    ayahCount: 98,
  },
  {
    id: 20,
    name: 'طه',
    englishName: 'Taa-Haa',
    germanName: 'Ta Ha',
    revelationType: 'Meccan',
    ayahCount: 135,
  },
  {
    id: 21,
    name: 'الأَنبِيَاءِ',
    englishName: 'Al-Anbiyaa',
    germanName: 'Die Propheten',
    revelationType: 'Meccan',
    ayahCount: 112,
  },
  {
    id: 22,
    name: 'الحَجِّ',
    englishName: 'Al-Hajj',
    germanName: 'Die Pilgerfahrt',
    revelationType: 'Medinan',
    ayahCount: 78,
  },
  {
    id: 23,
    name: 'المُؤۡمِنُونَ',
    englishName: 'Al-Muminoon',
    germanName: 'Die Gläubigen',
    revelationType: 'Meccan',
    ayahCount: 118,
  },
  {
    id: 24,
    name: 'النُّورِ',
    englishName: 'An-Noor',
    germanName: 'Das Licht',
    revelationType: 'Medinan',
    ayahCount: 64,
  },
  {
    id: 25,
    name: 'الفُرۡقَانِ',
    englishName: 'Al-Furqaan',
    germanName: 'Die Unterscheidung',
    revelationType: 'Meccan',
    ayahCount: 77,
  },
  {
    id: 26,
    name: 'الشُّعَرَاءِ',
    englishName: "Ash-Shu'araa",
    germanName: 'Die Dichter',
    revelationType: 'Meccan',
    ayahCount: 227,
  },
  {
    id: 27,
    name: 'النَّمۡلِ',
    englishName: 'An-Naml',
    germanName: 'Die Ameisen',
    revelationType: 'Meccan',
    ayahCount: 93,
  },
  {
    id: 28,
    name: 'القَصَصِ',
    englishName: 'Al-Qasas',
    germanName: 'Die Geschichten',
    revelationType: 'Meccan',
    ayahCount: 88,
  },
  {
    id: 29,
    name: 'العَنكَبُوتِ',
    englishName: 'Al-Ankaboot',
    germanName: 'Die Spinne',
    revelationType: 'Meccan',
    ayahCount: 69,
  },
  {
    id: 30,
    name: 'الرُّومِ',
    englishName: 'Ar-Room',
    germanName: 'Die Römer',
    revelationType: 'Meccan',
    ayahCount: 60,
  },
  {
    id: 31,
    name: 'لُقۡمَانَ',
    englishName: 'Luqman',
    germanName: 'Luqman',
    revelationType: 'Meccan',
    ayahCount: 34,
  },
  {
    id: 32,
    name: 'السَّجۡدَةِ',
    englishName: 'As-Sajda',
    germanName: 'Die Niederwerfung',
    revelationType: 'Meccan',
    ayahCount: 30,
  },
  {
    id: 33,
    name: 'الأَحۡزَابِ',
    englishName: 'Al-Ahzaab',
    germanName: 'Die Parteien',
    revelationType: 'Medinan',
    ayahCount: 73,
  },
  {
    id: 34,
    name: 'سَبَإٍ',
    englishName: 'Sheba',
    germanName: 'Saba',
    revelationType: 'Meccan',
    ayahCount: 54,
  },
  {
    id: 35,
    name: 'فَاطِرٍ',
    englishName: 'Faatir',
    germanName: 'Der Schöpfer',
    revelationType: 'Meccan',
    ayahCount: 45,
  },
  {
    id: 36,
    name: 'يسٓ',
    englishName: 'Yaseen',
    germanName: 'Ya-Sin',
    revelationType: 'Meccan',
    ayahCount: 83,
  },
  {
    id: 37,
    name: 'الصَّافَّاتِ',
    englishName: 'As-Saaffaat',
    germanName: 'Die in Reihen Stehenden',
    revelationType: 'Meccan',
    ayahCount: 182,
  },
  {
    id: 38,
    name: 'صٓ',
    englishName: 'Saad',
    germanName: 'Sad',
    revelationType: 'Meccan',
    ayahCount: 88,
  },
  {
    id: 39,
    name: 'الزُّمَرِ',
    englishName: 'Az-Zumar',
    germanName: 'Die Scharen',
    revelationType: 'Meccan',
    ayahCount: 75,
  },
  {
    id: 40,
    name: 'غَافِرٍ',
    englishName: 'Ghafir',
    germanName: 'Der Vergebende',
    revelationType: 'Meccan',
    ayahCount: 85,
  },
  {
    id: 41,
    name: 'فُصِّلَتۡ',
    englishName: 'Fussilat',
    germanName: 'Ausführlich dargelegt',
    revelationType: 'Meccan',
    ayahCount: 54,
  },
  {
    id: 42,
    name: 'الشُّورَىٰ',
    englishName: 'Ash-Shura',
    germanName: 'Die Beratung',
    revelationType: 'Meccan',
    ayahCount: 53,
  },
  {
    id: 43,
    name: 'الزُّخۡرُفِ',
    englishName: 'Az-Zukhruf',
    germanName: 'Der Goldschmuck',
    revelationType: 'Meccan',
    ayahCount: 89,
  },
  {
    id: 44,
    name: 'الدُّخَانِ',
    englishName: 'Ad-Dukhaan',
    germanName: 'Der Rauch',
    revelationType: 'Meccan',
    ayahCount: 59,
  },
  {
    id: 45,
    name: 'الجَاثِيَةِ',
    englishName: 'Al-Jaathiya',
    germanName: 'Das Knien',
    revelationType: 'Meccan',
    ayahCount: 37,
  },
  {
    id: 46,
    name: 'الأَحۡقَافِ',
    englishName: 'Al-Ahqaf',
    germanName: 'Die Sanddünen',
    revelationType: 'Meccan',
    ayahCount: 35,
  },
  {
    id: 47,
    name: 'مُحَمَّدٍ',
    englishName: 'Muhammad',
    germanName: 'Mohammed',
    revelationType: 'Medinan',
    ayahCount: 38,
  },
  {
    id: 48,
    name: 'الفَتۡحِ',
    englishName: 'Al-Fath',
    germanName: 'Der Sieg',
    revelationType: 'Medinan',
    ayahCount: 29,
  },
  {
    id: 49,
    name: 'الحُجُرَاتِ',
    englishName: 'Al-Hujuraat',
    germanName: 'Die Gemächer',
    revelationType: 'Medinan',
    ayahCount: 18,
  },
  {
    id: 50,
    name: 'قٓ',
    englishName: 'Qaaf',
    germanName: 'Qaf',
    revelationType: 'Meccan',
    ayahCount: 45,
  },
  {
    id: 51,
    name: 'الذَّارِيَاتِ',
    englishName: 'Adh-Dhaariyat',
    germanName: 'Das Aufwirbeln',
    revelationType: 'Meccan',
    ayahCount: 60,
  },
  {
    id: 52,
    name: 'الطُّورِ',
    englishName: 'At-Tur',
    germanName: 'Der Berg',
    revelationType: 'Meccan',
    ayahCount: 49,
  },
  {
    id: 53,
    name: 'النَّجۡمِ',
    englishName: 'An-Najm',
    germanName: 'Der Stern',
    revelationType: 'Meccan',
    ayahCount: 62,
  },
  {
    id: 54,
    name: 'القَمَرِ',
    englishName: 'Al-Qamar',
    germanName: 'Der Mond',
    revelationType: 'Meccan',
    ayahCount: 55,
  },
  {
    id: 55,
    name: 'الرَّحۡمَٰن',
    englishName: 'Ar-Rahmaan',
    germanName: 'Der Allerbarmer',
    revelationType: 'Medinan',
    ayahCount: 78,
  },
  {
    id: 56,
    name: 'الوَاقِعَةِ',
    englishName: 'Al-Waaqia',
    germanName: 'Das Eintreffende',
    revelationType: 'Meccan',
    ayahCount: 96,
  },
  {
    id: 57,
    name: 'الحَدِيدِ',
    englishName: 'Al-Hadid',
    germanName: 'Das Eisen',
    revelationType: 'Medinan',
    ayahCount: 29,
  },
  {
    id: 58,
    name: 'المُجَادلَةِ',
    englishName: 'Al-Mujaadila',
    germanName: 'Der Streit',
    revelationType: 'Medinan',
    ayahCount: 22,
  },
  {
    id: 59,
    name: 'الحَشۡرِ',
    englishName: 'Al-Hashr',
    germanName: 'Die Versammlung',
    revelationType: 'Medinan',
    ayahCount: 24,
  },
  {
    id: 60,
    name: 'المُمۡتَحنَةِ',
    englishName: 'Al-Mumtahana',
    germanName: 'Die Prüfung',
    revelationType: 'Medinan',
    ayahCount: 13,
  },
  {
    id: 61,
    name: 'الصَّفِّ',
    englishName: 'As-Saff',
    germanName: 'Die Reihe',
    revelationType: 'Medinan',
    ayahCount: 14,
  },
  {
    id: 62,
    name: 'الجُمُعَةِ',
    englishName: "Al-Jumu'a",
    germanName: 'Der Freitag',
    revelationType: 'Medinan',
    ayahCount: 11,
  },
  {
    id: 63,
    name: 'المُنَافِقُونَ',
    englishName: 'Al-Munaafiqoon',
    germanName: 'Die Heuchler',
    revelationType: 'Medinan',
    ayahCount: 11,
  },
  {
    id: 64,
    name: 'التَّغَابُنِ',
    englishName: 'At-Taghaabun',
    germanName: 'Die Übervorteilung',
    revelationType: 'Medinan',
    ayahCount: 18,
  },
  {
    id: 65,
    name: 'الطَّلَاقِ',
    englishName: 'At-Talaaq',
    germanName: 'Die Scheidung',
    revelationType: 'Medinan',
    ayahCount: 12,
  },
  {
    id: 66,
    name: 'التَّحۡرِيمِ',
    englishName: 'At-Tahrim',
    germanName: 'Das Verbot',
    revelationType: 'Medinan',
    ayahCount: 12,
  },
  {
    id: 67,
    name: 'المُلۡكِ',
    englishName: 'Al-Mulk',
    germanName: 'Die Herrschaft',
    revelationType: 'Meccan',
    ayahCount: 30,
  },
  {
    id: 68,
    name: 'القَلَمِ',
    englishName: 'Al-Qalam',
    germanName: 'Die Schreibfeder',
    revelationType: 'Meccan',
    ayahCount: 52,
  },
  {
    id: 69,
    name: 'الحَاقَّةِ',
    englishName: 'Al-Haaqqa',
    germanName: 'Die Wahrheit',
    revelationType: 'Meccan',
    ayahCount: 52,
  },
  {
    id: 70,
    name: 'المَعَارِجِ',
    englishName: "Al-Ma'aarij",
    germanName: 'Die Aufstiegswege',
    revelationType: 'Meccan',
    ayahCount: 44,
  },
  {
    id: 71,
    name: 'نُوحٍ',
    englishName: 'Nooh',
    germanName: 'Noah',
    revelationType: 'Meccan',
    ayahCount: 28,
  },
  {
    id: 72,
    name: 'الجِنِّ',
    englishName: 'Al-Jinn',
    germanName: 'Die Dschinn',
    revelationType: 'Meccan',
    ayahCount: 28,
  },
  {
    id: 73,
    name: 'المُزَّمِّلِ',
    englishName: 'Al-Muzzammil',
    germanName: 'Der Eingehüllte',
    revelationType: 'Meccan',
    ayahCount: 20,
  },
  {
    id: 74,
    name: 'المُدَّثِّرِ',
    englishName: 'Al-Muddaththir',
    germanName: 'Der Zugedeckte',
    revelationType: 'Meccan',
    ayahCount: 56,
  },
  {
    id: 75,
    name: 'القِيَامَةِ',
    englishName: 'Al-Qiyaama',
    germanName: 'Die Auferstehung',
    revelationType: 'Meccan',
    ayahCount: 40,
  },
  {
    id: 76,
    name: 'الإِنسَانِ',
    englishName: 'Al-Insaan',
    germanName: 'Der Mensch',
    revelationType: 'Medinan',
    ayahCount: 31,
  },
  {
    id: 77,
    name: 'المُرۡسَلَاتِ',
    englishName: 'Al-Mursalaat',
    germanName: 'Die Gesandten',
    revelationType: 'Meccan',
    ayahCount: 50,
  },
  {
    id: 78,
    name: 'النَّبَإِ',
    englishName: 'An-Naba',
    germanName: 'Die Ankündigung',
    revelationType: 'Meccan',
    ayahCount: 40,
  },
  {
    id: 79,
    name: 'النَّازِعَاتِ',
    englishName: "An-Naazi'aat",
    germanName: 'Die Entreißenden',
    revelationType: 'Meccan',
    ayahCount: 46,
  },
  {
    id: 80,
    name: 'عَبَسَ',
    englishName: 'Abasa',
    germanName: 'Er runzelte die Stirn',
    revelationType: 'Meccan',
    ayahCount: 42,
  },
  {
    id: 81,
    name: 'التَّكۡوِيرِ',
    englishName: 'At-Takwir',
    germanName: 'Das Einhüllen',
    revelationType: 'Meccan',
    ayahCount: 29,
  },
  {
    id: 82,
    name: 'الانفِطَارِ',
    englishName: 'Al-Infitaar',
    germanName: 'Die Spaltung',
    revelationType: 'Meccan',
    ayahCount: 19,
  },
  {
    id: 83,
    name: 'المُطَفِّفِينَ',
    englishName: 'Al-Mutaffifin',
    germanName: 'Die Betrüger',
    revelationType: 'Meccan',
    ayahCount: 36,
  },
  {
    id: 84,
    name: 'الانشِقَاقِ',
    englishName: 'Al-Inshiqaaq',
    germanName: 'Das Zerbrechen',
    revelationType: 'Meccan',
    ayahCount: 25,
  },
  {
    id: 85,
    name: 'البُرُوجِ',
    englishName: 'Al-Burooj',
    germanName: 'Die Türme',
    revelationType: 'Meccan',
    ayahCount: 22,
  },
  {
    id: 86,
    name: 'الطَّارِقِ',
    englishName: 'At-Taariq',
    germanName: 'Der bei Nacht Kommende',
    revelationType: 'Meccan',
    ayahCount: 17,
  },
  {
    id: 87,
    name: 'الأَعۡلَىٰ',
    englishName: "Al-A'laa",
    germanName: 'Der Allerhöchste',
    revelationType: 'Meccan',
    ayahCount: 19,
  },
  {
    id: 88,
    name: 'الغَاشِيَةِ',
    englishName: 'Al-Ghaashiya',
    germanName: 'Die Bedeckende',
    revelationType: 'Meccan',
    ayahCount: 26,
  },
  {
    id: 89,
    name: 'الفَجۡرِ',
    englishName: 'Al-Fajr',
    germanName: 'Die Morgendämmerung',
    revelationType: 'Meccan',
    ayahCount: 30,
  },
  {
    id: 90,
    name: 'البَلَدِ',
    englishName: 'Al-Balad',
    germanName: 'Die Stadt',
    revelationType: 'Meccan',
    ayahCount: 20,
  },
  {
    id: 91,
    name: 'الشَّمۡسِ',
    englishName: 'Ash-Shams',
    germanName: 'Die Sonne',
    revelationType: 'Meccan',
    ayahCount: 15,
  },
  {
    id: 92,
    name: 'اللَّيۡلِ',
    englishName: 'Al-Lail',
    germanName: 'Die Nacht',
    revelationType: 'Meccan',
    ayahCount: 21,
  },
  {
    id: 93,
    name: 'الضُّحَىٰ',
    englishName: 'Ad-Dhuhaa',
    germanName: 'Der Morgen',
    revelationType: 'Meccan',
    ayahCount: 11,
  },
  {
    id: 94,
    name: 'الشَّرۡحِ',
    englishName: 'Ash-Sharh',
    germanName: 'Das Weiten',
    revelationType: 'Meccan',
    ayahCount: 8,
  },
  {
    id: 95,
    name: 'التِّينِ',
    englishName: 'At-Tin',
    germanName: 'Die Feige',
    revelationType: 'Meccan',
    ayahCount: 8,
  },
  {
    id: 96,
    name: 'العَلَقِ',
    englishName: 'Al-Alaq',
    germanName: 'Der Blutklumpen',
    revelationType: 'Meccan',
    ayahCount: 19,
  },
  {
    id: 97,
    name: 'القَدۡرِ',
    englishName: 'Al-Qadr',
    germanName: 'Die Bestimmung',
    revelationType: 'Meccan',
    ayahCount: 5,
  },
  {
    id: 98,
    name: 'البَيِّنَةِ',
    englishName: 'Al-Bayyina',
    germanName: 'Der klare Beweis',
    revelationType: 'Medinan',
    ayahCount: 8,
  },
  {
    id: 99,
    name: 'الزَّلۡزَلَةِ',
    englishName: 'Az-Zalzala',
    germanName: 'Das Beben',
    revelationType: 'Medinan',
    ayahCount: 8,
  },
  {
    id: 100,
    name: 'العَادِيَاتِ',
    englishName: 'Al-Aadiyaat',
    germanName: 'Die Rennenden',
    revelationType: 'Meccan',
    ayahCount: 11,
  },
  {
    id: 101,
    name: 'القَارِعَةِ',
    englishName: "Al-Qaari'a",
    germanName: 'Die Polternde',
    revelationType: 'Meccan',
    ayahCount: 11,
  },
  {
    id: 102,
    name: 'التَّكَاثُرِ',
    englishName: 'At-Takaathur',
    germanName: 'Das Streben nach Mehr',
    revelationType: 'Meccan',
    ayahCount: 8,
  },
  {
    id: 103,
    name: 'العَصۡرِ',
    englishName: 'Al-Asr',
    germanName: 'Der Nachmittag',
    revelationType: 'Meccan',
    ayahCount: 3,
  },
  {
    id: 104,
    name: 'الهُمَزَةِ',
    englishName: 'Al-Humaza',
    germanName: 'Der Stichler',
    revelationType: 'Meccan',
    ayahCount: 9,
  },
  {
    id: 105,
    name: 'الفِيلِ',
    englishName: 'Al-Fil',
    germanName: 'Der Elefant',
    revelationType: 'Meccan',
    ayahCount: 5,
  },
  {
    id: 106,
    name: 'قُرَيۡشٍ',
    englishName: 'Quraish',
    germanName: 'Die Quraisch',
    revelationType: 'Meccan',
    ayahCount: 4,
  },
  {
    id: 107,
    name: 'المَاعُونِ',
    englishName: "Al-Maa'un",
    germanName: 'Die Hilfeleistung',
    revelationType: 'Meccan',
    ayahCount: 7,
  },
  {
    id: 108,
    name: 'الكَوۡثَرِ',
    englishName: 'Al-Kawthar',
    germanName: 'Die Fülle',
    revelationType: 'Meccan',
    ayahCount: 3,
  },
  {
    id: 109,
    name: 'الكَافِرُونَ',
    englishName: 'Al-Kaafiroon',
    germanName: 'Die Ungläubigen',
    revelationType: 'Meccan',
    ayahCount: 6,
  },
  {
    id: 110,
    name: 'النَّصۡرِ',
    englishName: 'An-Nasr',
    germanName: 'Die Hilfe',
    revelationType: 'Medinan',
    ayahCount: 3,
  },
  {
    id: 111,
    name: 'المَسَدِ',
    englishName: 'Al-Masad',
    germanName: 'Der Palmfaserstrick',
    revelationType: 'Meccan',
    ayahCount: 5,
  },
  {
    id: 112,
    name: 'الإِخۡلَاصِ',
    englishName: 'Al-Ikhlaas',
    germanName: 'Die Aufrichtigkeit',
    revelationType: 'Meccan',
    ayahCount: 4,
  },
  {
    id: 113,
    name: 'الفَلَقِ',
    englishName: 'Al-Falaq',
    germanName: 'Das Frühlicht',
    revelationType: 'Meccan',
    ayahCount: 5,
  },
  {
    id: 114,
    name: 'النَّاسِ',
    englishName: 'Mankind',
    germanName: 'Die Menschen',
    revelationType: 'Meccan',
    ayahCount: 6,
  },
];
