export const SW_EVENTS = {
  DOWNLOAD_TRACK: 'DOWNLOAD_TRACK',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',

  ESTIMATE_SIZE: 'ESTIMATE_SIZE',
  SIZE_RESULT: 'SIZE_RESULT',

  PAUSE_DOWNLOAD: 'PAUSE_DOWNLOAD',
  RESUME_DOWNLOAD: 'RESUME_DOWNLOAD',
  CANCEL_DOWNLOAD: 'CANCEL_DOWNLOAD',

  GET_STORAGE_STATS: 'GET_STORAGE_STATS',
  CLEAR_ALL_TRACKS: 'CLEAR_ALL_TRACKS',

  CLEAR_AUDIO: 'CLEAR_AUDIO',
  CLEAR_TRACK: 'CLEAR_TRACK',
  PING: 'PING',
  PONG: 'PONG',
} as const;
